#!/usr/bin/env python3
"""Gather what every kit component says about itself, and who calls it.

WHY. There are thirty-six of these and the only account of why each exists,
what it replaced and what it refused to flatten is the comment at the top of
the file. Those headers are the best documentation in this estate — they record
the measurement that prompted the component and the capability that would have
been lost — and nothing gathers them. So the next «is there already a component
for this?» is a grep across thirty-six files, and the answer is easy to miss.

WHAT IT CANNOT KNOW: whether a component SHOULD have more callers. A component
used once may be a fork waiting to happen or may be right — that is a reading,
and the register of shared pages is where it is written down. This only reports
who calls what.

  python3 kit/tools/components.py --root <estate dir> [--write]

Without --write it prints; with --write it puts the index in kit/docs/.
"""
import argparse, io, os, re, sys, glob

# Eight, not seven. Luwinski was missing from this list until 21 September
# 2026, so every count this file has ever printed was short by one archive and
# nothing Luwinski called was ever credited. And the directory is "D'arcy
# Family" with a small a — the spelling below only ever matched because macOS
# does not care, and it would find nothing on a case-sensitive disk.
ARCHIVES = ["Falco Family", "Defranceski Family", "Booyzen Family", "D'arcy Family",
            "Blazevic Family", "Mazza Family", "Lerena Family", "Luwinski Family"]


def blurb(src):
    """The component's own first sentence, out of whichever comment style it uses."""
    m = re.search(r"/\*(.*?)\*/", src, re.S)
    if not m:
        return ""
    body = m.group(1)
    lines = [re.sub(r"^\s*\*?\s?", "", l).rstrip() for l in body.split("\n")]
    text = " ".join(l for l in lines if l.strip())
    text = re.sub(r"\s+", " ", text).strip()
    # first sentence, allowing for «Mr.»-style stops by requiring a capital after
    m2 = re.search(r"^(.+?[.!?])(?:\s+[A-Z«]|$)", text)
    return (m2.group(1) if m2 else text)[:400]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=".")
    ap.add_argument("--write", action="store_true")
    a = ap.parse_args()
    root = os.path.abspath(a.root)
    kit = os.path.join(root, "Archive Kit")
    if not os.path.isdir(kit):
        kit = root                      # already inside the kit
        root = os.path.dirname(kit)

    comps = sorted(glob.glob(os.path.join(kit, "kit", "components", "*.astro")))
    # every archive's source, read once
    sources = {}
    for arch in ARCHIVES:
        p = os.path.join(root, arch, "site", "src")
        if not os.path.isdir(p):
            continue
        blob = []
        for f in glob.glob(p + "/**/*.astro", recursive=True) + glob.glob(p + "/**/*.js", recursive=True):
            try:
                blob.append(io.open(f, encoding="utf-8", errors="ignore").read())
            except OSError:
                pass
        sources[arch] = "\n".join(blob)

    rows = []
    for f in comps:
        name = os.path.basename(f)[:-6]
        src = io.open(f, encoding="utf-8").read()
        # The mark must name the KIT's copy. "components/Sources.astro" also
        # matches an archive's own ../components/Sources.astro, and Defranceski
        # has exactly that — a local SourceBlock predating the kit's — so the
        # loose match credited the kit with a component it was not supplying.
        mark = "archive-kit/components/%s.astro" % name
        callers = [arch.split()[0] for arch, blob in sources.items() if mark in blob]
        # a component the kit itself draws with, which is not the same as an archive calling it
        inner = [os.path.basename(g)[:-6] for g in comps
                 if g != f and ('./%s.astro' % name) in io.open(g, encoding="utf-8").read()]
        rows.append((name, blurb(src), callers, inner, len(src)))

    out = []
    out.append("# What is in the kit\n")
    out.append("Generated by `kit/tools/components.py`. Every line is the component's own first\n"
               "sentence: the headers are where this estate keeps the reason each thing exists,\n"
               "what it replaced, and what it refused to flatten on the way.\n")
    used = [r for r in rows if r[2] or r[3]]
    orphan = [r for r in rows if not r[2] and not r[3]]
    out.append("**%d components.** %d are called by an archive or by another component; "
               "%d are not called anywhere.\n" % (len(rows), len(used), len(orphan)))
    out.append("\n| Component | What it is | Archives | Drawn by |")
    out.append("| --- | --- | --- | --- |")
    for name, b, callers, inner, _ in rows:
        who = "%d — %s" % (len(callers), ", ".join(callers)) if callers else "—"
        out.append("| `%s` | %s | %s | %s |" % (name, b.replace("|", "\\|"), who,
                                                ", ".join("`%s`" % i for i in inner) or "—"))
    if orphan:
        out.append("\n## Called by nothing\n")
        out.append("Not necessarily wrong — a component can be written before the page that needs\n"
                   "it — but each of these is either waiting for a caller or is dead.\n")
        for name, b, _, _, size in orphan:
            out.append("- **`%s`** (%d bytes) — %s" % (name, size, b))
    text = "\n".join(out) + "\n"

    if a.write:
        p = os.path.join(kit, "kit", "docs", "components.md")
        os.makedirs(os.path.dirname(p), exist_ok=True)
        io.open(p, "w", encoding="utf-8").write(text)
        print("  written %s — %d components, %d with no caller" % (p, len(rows), len(orphan)))
    else:
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
