#!/usr/bin/env python3
"""What is staged, and whose is it?

Eight archives are built out of one checkout by concurrent sessions, and on
22 September 2026 a file written by one session was published by another
FOUR times in one evening, by three different sessions. Every one was staged
with a directory pattern — `git add -A`, `git add site/src site/public` —
over a directory holding somebody else's unstaged work. Twice it was a kit
pin bump, once fifty-one lines of the shared stylesheet, once both.

NONE OF THE FOUR WAS WRONG TO HAVE. All four were wrong to publish without
knowing. A commit message that does not mention half of what the commit
contains is a false statement about the work, and it is the kind that
survives, because `git log` is where the next reader looks.

The defence cannot live with the author of the swept file: you cannot stage
defensively against somebody else's `git add`. It has to run on the staging
end, which means every archive needs it, which is why it is here rather
than in the one repository that thought of it. The original is
Defranceski's `scripts/whose.sh`, written after it happened there twice;
this is that idea with the classification made per-archive and the diff
shown rather than only the path.

    python3 whose.py                  # before a commit
    python3 whose.py --allow-shared   # yes, I meant that stylesheet
    python3 whose.py --quiet          # only speak when it refuses

IT REFUSES RATHER THAN WARNING, which is the only interesting decision in
it. A warning in a transcript is a warning nobody reads.

WHAT COUNTS AS SHARED. Ground another session owns: the estate stylesheet,
layouts, components, the nav, the kit pin and lockfile, and anything at the
repository root. What counts as MINE is this archive's own evidence and
pages. The default below is right for most of the eight and wrong for some
— Defranceski's `site/public/searchindex.json` is generated here and owned
here — so an archive states its own exceptions in `.whose` at its root:

    mine:   site/public/searchindex.json    # generated by tools/index.py
    shared: site/src/data/archives.json     # the ring, edited estate-wide

One rule per line, `mine:` or `shared:` then a glob, `#` for a comment.
Printed on every run, like `.harmonise-exempt`, because a rule nobody reads
is a rule nobody revisits.
"""

import argparse, fnmatch, os, subprocess, sys

MINE = ["site/src/data/*", "site/src/pages/*", "site/src/lib/*",
        "scripts/*", "tools/*", "data/*", "sources/*", "notes/*",
        "requests/*", "docs/*", ".rowfloor",
        # No markdown in this estate is shared between archives: each
        # repository carries its own README and its own notes, and the kit
        # lives in a repository of its own. Checked before classifying.
        "*.md"]
SHARED = ["site/public/*", "site/src/layouts/*", "site/src/components/*",
          "site/src/styles/*", "site/package.json", "site/package-lock.json",
          "*/kit/*", ".gitignore", ".harmonise-exempt", ".inline-exempt"]


def rules(root):
    """The archive's own exceptions, and the line each one came from."""
    out = []
    p = os.path.join(root, ".whose")
    if not os.path.isfile(p):
        return out
    for n, line in enumerate(open(p, encoding="utf-8"), 1):
        line = line.split("#")[0].strip()
        if not line or ":" not in line:
            continue
        side, pat = line.split(":", 1)
        side, pat = side.strip().lower(), pat.strip()
        if side in ("mine", "shared") and pat:
            out.append((side, pat, n))
    return out


def side_of(path, extra):
    # An archive's own rule beats the default, and a later rule beats an
    # earlier one, so a file can be reclassified without deleting a line.
    verdict = None
    for side, pat, _ in extra:
        if fnmatch.fnmatch(path, pat):
            verdict = side
    if verdict:
        return verdict
    for pat in MINE:
        if fnmatch.fnmatch(path, pat):
            return "mine"
    for pat in SHARED:
        if fnmatch.fnmatch(path, pat):
            return "shared"
    # THE DEFAULT IS SHARED, NOT MINE. A path nobody has classified is a path
    # nobody has thought about, and the failure that matters is publishing
    # somebody else's work rather than being asked about your own.
    return "shared"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=".")
    ap.add_argument("--allow-shared", action="store_true")
    ap.add_argument("--quiet", action="store_true")
    a = ap.parse_args()

    try:
        staged = subprocess.run(["git", "-C", a.root, "diff", "--cached", "--name-only"],
                                capture_output=True, text=True, check=True).stdout.split()
    except (subprocess.CalledProcessError, FileNotFoundError):
        print("  --    whose      not run: no git here")
        return 0
    if not staged:
        if not a.quiet:
            print("  ok    whose      nothing staged")
        return 0

    extra = rules(a.root)
    mine = [f for f in staged if side_of(f, extra) == "mine"]
    shared = [f for f in staged if side_of(f, extra) == "shared"]

    if not a.quiet or shared:
        for pat_side, pat, n in extra:
            print("        .whose:%-3d %s: %s" % (n, pat_side, pat))
        if mine:
            print("  MINE   %d file(s)" % len(mine))
            for f in mine:
                print("           " + f)
    if shared:
        print("  SHARED GROUND  %d file(s) — another session may own these" % len(shared))
        for f in shared:
            stat = subprocess.run(["git", "-C", a.root, "diff", "--cached", "--shortstat", "--", f],
                                  capture_output=True, text=True).stdout.strip()
            print("           %-52s %s" % (f, stat or "(no textual change)"))
        if not a.allow_shared:
            print("\n  FAIL  whose      shared ground is staged and --allow-shared was not given.")
            print("        Unstage it, or say what it is in the commit message and pass the flag.")
            return 1
        print("  ok    whose      %d shared file(s), allowed explicitly" % len(shared))
        return 0
    if not a.quiet:
        print("  ok    whose      %d file(s), all this archive's own" % len(mine))
    return 0


if __name__ == "__main__":
    sys.exit(main())
