#!/usr/bin/env python3
"""One board for the whole estate, built from the archives rather than typed.

The reason there were seven documents is that each was written by hand to answer
one question on one day, and a hand-written board is out of date the moment
somebody else commits. This reads every archive's worklist.json and emits the
single page — so the board cannot disagree with the archives, because it IS the
archives.

  python3 worklist_rollup.py --root /path/to/Projects --out board.html
"""
import os, re, sys, json, glob, html, argparse, datetime

STATE = {
    "running": ("Running", "#1E5F8C", "a machine or a person is at it now"),
    "next":    ("Next",    "#E9A020", "ready to start"),
    "blocked": ("Blocked", "#B04A16", "waiting on a person or an institution"),
    "done":    ("Done",    "#12703F", "finished and published"),
    "struck":  ("Struck",  "#7A7A7A", "founded on a mistake, kept rather than deleted"),
}
ORDER = ["blocked", "running", "next", "done", "struck"]
E = lambda s: html.escape(str(s or ""))


def md(s):
    s = E(s)
    s = re.sub(r'\[([^\]]+)\]\(([^)]*)\)', r'<a href="\2">\1</a>', s)
    s = re.sub(r'\*\*([^*]+)\*\*', r'<strong>\1</strong>', s)
    return re.sub(r'«([^»]+)»', r'<em>«\1»</em>', s)


def load(root):
    out = []
    # the kit carries the estate's own list: gates, shared components, and the
    # items that are nobody's archive but everybody's problem
    kp = os.path.join(root, "Archive Kit", "worklist.json")
    if os.path.exists(kp):
        try:
            out.append(("the kit & estate", (json.load(open(kp, encoding="utf-8")) or {}).get("rows") or [], None))
        except Exception as e:
            out.append(("the kit & estate", None, str(e)))
    for p in sorted(glob.glob(os.path.join(root, "*", "site", "src", "data", "worklist.json"))):
        name = os.path.relpath(p, root).split(os.sep)[0].replace(" Family", "")
        try:
            w = json.load(open(p, encoding="utf-8"))
        except Exception as e:
            out.append((name, None, str(e))); continue
        out.append((name, w.get("rows") or [], None))
    missing = []
    for d in sorted(glob.glob(os.path.join(root, "*", "site"))):
        name = os.path.relpath(d, root).split(os.sep)[0]
        if not os.path.exists(os.path.join(d, "src", "data", "worklist.json")):
            missing.append(name.replace(" Family", ""))
    return out, missing


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=".")
    ap.add_argument("--out", default="board.html")
    a = ap.parse_args()
    archives, missing = load(a.root)

    rows = []
    for name, rs, err in archives:
        for r in (rs or []):
            rows.append({**r, "archive": name})

    def key(r):
        return (ORDER.index(r.get("state")) if r.get("state") in ORDER else 9,
                r.get("archive", ""), r.get("n") or 0)
    rows.sort(key=key)
    openrows = [r for r in rows if r.get("state") in ("blocked", "running", "next")]

    who = {}
    for r in openrows:
        who.setdefault((r.get("owner") or "nobody named").strip(), []).append(r)

    P = []
    P.append("<!-- generated by worklist_rollup.py — edit the archives, not this -->")
    P.append('<p class="eyebrow">The estate board · generated %s</p>'
             % datetime.date.today().isoformat())
    P.append("<div class='tally'>")
    for k in ORDER:
        n = sum(1 for r in rows if r.get("state") == k)
        if n:
            P.append("<div class='tal'><div class='n' style='color:%s'>%d</div>"
                     "<span class='l'>%s</span></div>" % (STATE[k][1], n, STATE[k][0].lower()))
    P.append("</div>")

    if missing:
        P.append("<div class='note bad'><b>%d of %d archives keep no work list yet.</b> %s. "
                 "Until they do, this board cannot show what they are carrying — and that is the "
                 "whole failure it exists to end.</div>"
                 % (len(missing), len(missing) + len(archives), E(", ".join(missing))))

    P.append("<h2>Open, by who has to move it</h2>")
    for owner in sorted(who, key=lambda o: (-len(who[o]), o)):
        P.append("<h3>%s <span class='c'>%d</span></h3>" % (E(owner), len(who[owner])))
        for r in who[owner]:
            lab, col, mean = STATE.get(r.get("state"), STATE["next"])
            P.append("<div class='one' style='border-left-color:%s'>"
                     "<div class='lab'><b style='color:%s'>%s</b> · %s%s</div>"
                     "<p class='what'>%s</p>%s</div>"
                     % (col, col, lab, E(r["archive"]),
                        " · raised " + E(r["since"]) if r.get("since") else "",
                        E(r.get("what")),
                        "<div class='note-p'>%s</div>" % md(r.get("note")) if r.get("note") else ""))

    P.append("<h2>Appendix — what is finished</h2>")
    for name, rs, err in archives:
        fin = [r for r in (rs or []) if r.get("state") in ("done", "struck")]
        if not fin:
            continue
        P.append("<h3>%s <span class='c'>%d</span></h3><ul class='done'>" % (E(name), len(fin)))
        for r in fin:
            P.append("<li%s>%s</li>" % (" class='struck'" if r.get("state") == "struck" else "",
                                        E(r.get("what"))))
        P.append("</ul>")
    open(a.out, "w", encoding="utf-8").write("\n".join(P))
    print("  %d archives, %d rows, %d open, %d without a list → %s"
          % (len(archives), len(rows), len(openrows), len(missing), a.out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
